{"uuid": "69751d16-f20c-41a1-aa91-a55deb250778", "children": ["4d27e0ea-7b3e-491c-bc0a-c6025a84e491"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1737262452932, "stop": 1737262452932}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Vishal\\PycharmProjects\\pytestautomationdemo\\Pages\\LoginPage.py\", line 29, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1737262457843, "stop": 1737262457847}], "start": 1737262452932, "stop": 1737262457847}