{"uuid": "dd65d7eb-bb14-4232-b640-99e57655c654", "children": ["2d9d8432-9811-444c-b97c-95d43e118339"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1737262612144, "stop": 1737262612144}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Vishal\\PycharmProjects\\pytestautomationdemo\\Pages\\LoginPage.py\", line 29, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1737262626281, "stop": 1737262626323}], "start": 1737262612144, "stop": 1737262626323}